var client = {
    name: '',
    access: '',
    accountOwner: '',
    category: '',
    websiteAddress: '',
    status: '',
    accountCode: '',
    phoneNumber1: '',
    phoneNumber2: '',
    country: '',
    state: '',
    city: '',
    street: '',
    zipCode: 0,
    fax: 0,
    email1: '',
    email2: '',
    description: ''
}
var requirement = {
    access: '',
    accountOwner: '',
    billRate: 0,
    briefDescription: '',
    category: '',
    city: '',
    country: '',
    description: '',
    duration: '',
    employementType: '',
    endClient: '',
    experienceLevel: '',
    interviewType: '',
    localIndicator: '',
    maxResumesAllowed: 0,
    notes: '',
    numberOfOpenings: 0,
    payRate: '',
    posiitonType: '',
    primaryRecruiteer: '',
    projectEndDate: '',
    projectStartDate: '',
    requiredExperience: '',
    requiredSkills: '',
    requirementId: 0,
    requirementTitle: '',
    state: '',
    status: '',
    subCategory: '',
    visaType: '',
    zipCode: ''
}
var candidate = {
    address: '',
    availableFrom: '',
    candidateId: '',
    candidateStatus: '',
    city: '',
    country: '',
    dateOfBirth: '',
    emailAddress: '',
    fatherName: '',
    fax: '',
    firstName: '',
    gender: '',
    hobbies: '',
    lastName: '',
    licenseNumber: '',
    linkedinUrl: '',
    maritalStatus: '',
    middleName: '',
    mobileNumber: '',
    motherName: '',
    nationality: '',
    noticePeriod: '',
    passportNumber: '',
    phoneNumber: '',
    preferredLocation1: '',
    preferredLocation2: '',
    skypeId: '',
    sourceBy: '',
    sourceFrom: '',
    sourceInfo: '',
    sourcing: '',
    state: '',
    visaStatus: '',
    zipCode: ''
}
var document = {
    name: '',
    type: '',
    issueDate: '',
    expiryDate: '',
    attachedBy: '',
    updatedBY: '',
    documentOwner:'',
    notes:'',
    document_id: ''
}
module.exports= {client: client, requirement:requirement, candidate:candidate, document:document}