export const LOAD_CATS_SUCCESS = 'LOAD_CATS_SUCCESS';
export const LOAD_HOBBIES_SUCCESS = 'LOAD_HOBBIES_SUCCESS';
export const UPDATE_CAT_SUCCESS = 'UPDATE_CAT_SUCCESS';
export const CREATE_CAT_SUCCESS = 'CREATE_CAT_SUCCESS';
export const DELETE_CAT_SUCCESS = 'DELETE_CAT_SUCCESS';
export const LOAD_REQUIREMENTS_SUCCESS = 'LOAD_REQUIREMENTS_SUCCESS';
export const LOAD_CANDIDATES_SUCCESS = 'LOAD_CANDIDATES_SUCCESS';
